# Generated by Django 5.2.8 on 2025-11-16 07:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
                'db_table': 'specialties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='consultants/avatar/')),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('years_of_experience', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('medical_degree', models.CharField(blank=True, max_length=200)),
                ('board_certifications', models.JSONField(blank=True, default=list)),
                ('additional_qualification', models.JSONField(blank=True, default=list)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must use the format: +91-[10 digit number]', regex='^\\+?91?\\d{9,15}$')])),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('clinic_address', models.TextField(blank=True, max_length=300)),
                ('clinic_city', models.CharField(blank=True, max_length=100)),
                ('clinic_country', models.CharField(blank=True, max_length=100)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('consultation_duration', models.PositiveIntegerField(default=50, help_text='Default consultation duration in minutes', validators=[django.core.validators.MaxValueValidator(50)])),
                ('consultation_types', models.CharField(choices=[('video', 'Video Consultation'), ('audio', 'Audio Only'), ('chat', 'Text Chat'), ('all', 'All Types')], default='all', max_length=10)),
                ('language_spoken', models.JSONField(blank=True, default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('availablity_schedule', models.JSONField(blank=True, default=dict, help_text='Weekly schedule with time slots')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_consultations', models.PositiveIntegerField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'consultant'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to=settings.AUTH_USER_MODEL)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultant_speciality', to='consultants.speciality')),
            ],
            options={
                'verbose_name': 'Consultant Profile',
                'verbose_name_plural': 'Consultant Profiles',
                'db_table': 'consultant_profile',
            },
        ),
        migrations.CreateModel(
            name='ConsultantAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to='consultants.consultantprofile')),
            ],
            options={
                'db_table': 'consultant_availability',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('consultant', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ConsultantReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')])),
                ('review_text', models.TextField(blank=True, max_length=100)),
                ('is_verified_consultation', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='consultants.consultantprofile')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patients'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultant_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['consultant', 'rating'], name='consultant__consult_2fdf5f_idx'), models.Index(fields=['created_at'], name='consultant__created_0e54a8_idx')],
                'unique_together': {('consultant', 'patient')},
            },
        ),
        migrations.AddIndex(
            model_name='consultantprofile',
            index=models.Index(fields=['user'], name='consultant__user_id_ea9b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='consultantprofile',
            index=models.Index(fields=['speciality'], name='consultant__special_8650c1_idx'),
        ),
        migrations.AddIndex(
            model_name='consultantprofile',
            index=models.Index(fields=['is_verified', 'is_available'], name='consultant__is_veri_a9dba0_idx'),
        ),
        migrations.AddIndex(
            model_name='consultantprofile',
            index=models.Index(fields=['created_at'], name='consultant__created_57f7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='consultantprofile',
            index=models.Index(fields=['rating'], name='consultant__rating_ccd26c_idx'),
        ),
    ]
